### ISSUE TITLE
Display/load replays

### ISSUE THREAD

**Issue by Flockana** [InvaderZim85/ManiaExchangeClient#2]
# Display/load replays

![bug](https://user-images.githubusercontent.com/44819259/48094823-7c273380-e213-11e8-93cc-11d1e5066706.gif)

**Issue:**
In the GIF you can see that the replays of the previous track are displayed. Only by changing the tabs the replays will be reloaded.

**Hint:**
If you restart the search for the tracks, then you can better select the tab "Track Full" again. So this problem would not occur.
Alternatively, the replays would have to be reloaded without having to click.

**Comment by InvaderZim85** [comment]
Fixed
