### ISSUE TITLE
Appearance Bug

### ISSUE THREAD

**Issue by Flockana** [InvaderZim85/ManiaExchangeClient#3]
# Appearance Bug
![themebug](https://user-images.githubusercontent.com/44819259/48097521-69fcc380-e21a-11e8-89d5-55cdcdbe5951.gif)

**Issue:**
If you adjust the appearance and then go directly to the x, then the appearance is retained. If you go under the settings again, you will see that the previous settings are there again. However, if you click on the "Close" button instead of the x, the appearance will be restored.

**Hint:**
Here the same function should be behind the x and the "Close" button. So if you press the x, you have to take the appearance that was saved last.

**Comment by InvaderZim85** [comment]
Fixed
